language: python
python:
  - '3.6'

# safelist
branches:
  only:
    - staging

before_script:
  - pip3 install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=gofacts_project.settings.travis

script:
  - python3 ./manage.py test