language: python
python:
  - '3.6'

##safelist
#branches:
#  only:
#    - staging

before_script:
  - pip install -r requirements.txt

env:
  - DJANGO_SETTINGS_MODULE="gofacts_project" ; - SECRET_KEY = "mS6p+68'zy@9x+,Bw&]'@-J9"

services:
  - postgresql

script: python manage.py test